apiVersion: v1
kind: Service
metadata:
  name: gopedia-mcp
  namespace: gopedia
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: gopedia-mcp
  type: ClusterIP

